site_name: Generative AI for Business
site_url: https://genaiforbusiness.github.io
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot-excited-outline
  favicon: assets/images/assistant_24dp_2854C5.png
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight

copyright: Copyright &copy; 2025 Midhubalan Balasubramanian
repo_url: https://github.com/genaiforbusiness/code-samples
repo_name: genaiforbusiness/code-samples
extra:
  generator: true
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/midhubalan
    - icon: fontawesome/brands/github-alt
      link: https://github.com/midhubalan 

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        #primary: indigo
        #accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        #primary: indigo
        #accent: indigo

plugins:
  - tags
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
      
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html
  - tables
  - toc:
      permalink: true
      title: On this page
  - abbr
  - attr_list
  - pymdownx.blocks.caption
# Emoji config
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Mermaid markdown config for diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# Code block display config
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tabbed content
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  # Formatting text
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Syllabus: 
    - syllabus/index.md
    - Course Description: syllabus/course-description.md
    - Course Materials: syllabus/course-materials.md
    - Grading & Evaluation: syllabus/grading.md
    - AI Project: 
        - syllabus/ai-project/index.md
        - Bootstrap: syllabus/ai-project/bootstrap.md
        - Project Charter: syllabus/ai-project/charter.md
        - Minimum Viable Product: syllabus/ai-project/mvp.md
        - Experimentation Report: syllabus/ai-project/refactor.md
        - Launch Kit: syllabus/ai-project/launch-kit.md
        - Project Peer Review: syllabus/ai-project/peer-review.md
        - Individual Contribution: syllabus/ai-project/individual-contribution.md
    - Tools: syllabus/tools.md
    - Schedule: syllabus/schedule.md
    - Course Policies: syllabus/course-policies.md
    - AI Policy: syllabus/ai-policy.md
    - Teaching Philosophy: syllabus/teaching-philosophy.md
  - Generative AI & LLMs:
    - llms/index.md
    - Models & Capabilities:
      - llms/foundational-models/index.md
      - Introduction to LLMs: llms/foundational-models/intro.md
      - Model Architecture: llms/foundational-models/architecture.md
      - Embeddings: llms/foundational-models/embeddings.md
      - Model Development: llms/foundational-models/model-development.md
      - Model Alignment: llms/foundational-models/reward-model.md
      - Try It Yourself: llms/foundational-models/activity.md
      - Conclusion & Next Steps: llms/foundational-models/next-steps.md
    - Model Selection:
      - llms/model-selection/index.md
      - Model Card: llms/model-selection/model-card.md
      - Guided Tour of Model Card: llms/model-selection/guided-tour.md
      - Model Choice & Business Alignment: llms/model-selection/align-model-choice.md
      - "Model Choice: Hands-on Activity": llms/model-selection/activity.md
      - Conclusion & Next Steps: llms/model-selection/next-steps.md
    - Embedding Models:
      - llms/embedding/index.md
      - Introduction to Embedding: llms/embedding/intro.md
      - A GPS for Meaning: llms/embedding/coordinates.md
      - Embedding Benchmark: llms/embedding/benchmark.md
      - Business Value: llms/embedding/business-value.md
      - Tradeoffs: llms/embedding/tradeoffs.md
      - Try It Yourself: llms/embedding/activity.md
      - Conclusion & Next Steps: llms/embedding/next-steps.md
  - Prompt Design:
    - prompts/index.md
    - Anatomy of a Prompt: 
      - prompts/anatomy/index.md
      - Introduction to Prompt Engineering: prompts/anatomy/intro.md
      - Prompt's Control Panel: prompts/anatomy/config.md
      - Hands-on Lab : prompts/anatomy/activity.md
      - Conclusion & Next Steps: prompts/anatomy/next-steps.md

    - Prompting Techniques:
      - prompts/techniques/index.md
      - Introduction: prompts/techniques/intro.md 
      - Essential Building Blocks: prompts/techniques/essentials.md
    - AI Safety & Ethics:
      - prompts/safety-ethics/index.md
    - Tapping Model Capabilities:
      - prompts/capabilities/index.md
    - Prompt Workflow:
      - prompts/workflow/index.md
  - Context Engineering:
    - contexts/index.md
  - Agents:
    - agents/index.md
